package com.xworkz.app.dto;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

import com.xworkz.classs.*;

public class CountryDTORunner {

	public CountryDTORunner(int i, String string, String string2, int j, boolean b, LocalDate of, int k, String string3,
			String string4, String string5, String string6, String string7) {
		// TODO Auto-generated constructor stub
	}

	public static void main(String[] args) {


				System.out.println("invoking main in Country Runner...");
				CountryDTORunner dto1=new CountryDTORunner(1, "Afghanistan", "Kabul", 42239854, true, LocalDate.of(1919, 7, 19), 34, "Sunni Islam", "Snow leopard", "Afghan snowfinch", "Buzkashi", "Abdullah");
		        CountryDTORunner dto2=new CountryDTORunner(2, "Albania", "Tirana", 	2832439, true, LocalDate.of(1912, 11, 28), 12, "Islam", "lion", "Aquila chrysaetos", "Soccer", "Edi Rama");
		        CountryDTORunner dto3=new CountryDTORunner(3, "Algeria", "Algiers", 45606480, true, LocalDate.of( 1962, 7, 5), 48, "Sunni Muslims", "Fennec fox ", "Barbary Partridge", "football", "Ahmed Ouyahia");
		        CountryDTORunner dto4=new CountryDTORunner(4, "Andorra", "Andorra la Vella",80088, true, LocalDate.of(1278, 9, 8), 10, "Roman Catholicism", "Brown Bear", "Partridge", "football", "Abdelmadjid Tebboune");
		        CountryDTORunner dto5=new CountryDTORunner(5, "Angola", "Luanda", 	36684202, false, LocalDate.of( 1975, 11, 11), 18, "Christianity", "Giant Sable Antelope", "Red-crested turaco", "football", " Joao Lourenco");
		        CountryDTORunner dto6=new CountryDTORunner(6, "Antigua and Barbuda", "Saint John's", 94298, true, LocalDate.of( 1981, 11, 1), 6, "Christianity", " Hawksbill Turtle", "Magnificent frigatebird", "Cricket", "Gaston Browne");
		        CountryDTORunner dto7=new CountryDTORunner(7, "Argentina", "Buenos Aires", 45773884, false, LocalDate.of( 1816, 7, 9), 23, "Christianity", " Rufous Hornero", "Rufous hornero", "football", "Alberto Fernández");
		        CountryDTORunner dto8=new CountryDTORunner(8, "Armenia", "Yerevan",2777970, true, LocalDate.of( 1991, 9, 21), 11, "Christianity", "Armenian Highland Cattle", "Armenian gull", "Wrestling", "Nikol Pashinyan");
		        CountryDTORunner dto9=new CountryDTORunner(9, "Australia", "Canberra", 26439111, false, LocalDate.of( 1901, 1, 1), 6, "Christianity", "Kangaroo", "Emu", "Cricket", "Scott Morrison");
		        CountryDTORunner dto10=new CountryDTORunner(10, "Austria", "Vienna",8958960, true, LocalDate.of( 1955, 9, 26), 9, "Roman Catholic", " Austrian Eagle", "Barn swallow ", "football", "Sebastian Kurz");
		        CountryDTORunner dto11=new CountryDTORunner(11, "Azerbaijan", "Baku", 10412651, true, LocalDate.of( 1991, 9, 18), 66, "Shia Muslims", "Karabakh Horse", "Equus ferus caballus", "Gulesh", "Ali Asadov ");
		        CountryDTORunner dto12=new CountryDTORunner(12, " The Bahamas", "Nassau", 412623, true, LocalDate.of( 1973, 6, 10), 31, "Christianity", "Blue Marlin", "Flamingo", "Cricket", "Hubert Minnis");
		        CountryDTORunner dto13=new CountryDTORunner(13, "Bahrain", "Manama",1485509, false, LocalDate.of(1971,8,15), 11, "Shia Muslim", "Arabian Horse", "Phoenicopterus", "football", "Salman bin Hamad Al Khalifa ");
		        CountryDTORunner dto14=new CountryDTORunner(14, "Bangladesh", "Dhaka", 	172954319, true, LocalDate.of( 1971, 3, 26), 8, "Sunni Muslim", "Royal Bengal Tiger", "Oriental magpie-robin", "Cricket", "Sheikh Hasina");
		        CountryDTORunner dto15=new CountryDTORunner(15, "Barbados", "Bridgetown",281995, true, LocalDate.of( 1966, 11, 30), 11, "Christianity", "Barbados Green Monkey", "Copsychus saularis", "Cricket", " Mia Mottley");
		        CountryDTORunner dto16=new CountryDTORunner(16, "Belarus", "Minsk",9498238, false, LocalDate.of( 1990, 7, 27), 6, "Buddhism", "European Bison", "White stork", "Ice Hockey", "Alexander Lukashenko");
		        CountryDTORunner dto17=new CountryDTORunner(17, "Belgium", "Brussels",11686140, true, LocalDate.of( 1831, 7, 21), 3, "catholic", "Lion", "Ciconia ciconi", "Soccer", "Alexander De Croo");
		        CountryDTORunner dto18=new CountryDTORunner(18, "Belize", "Belmopan", 410825, false, LocalDate.of( 1981, 8, 21), 6, "Christianity", "Baird's Tapir", "Keel-billed toucan", "football", "John Briceno");
		        CountryDTORunner dto19=new CountryDTORunner(19, "Benin", "Porto-Novo", 13712828, true, LocalDate.of( 1960, 8, 1), 12, "Christianity", "African Lion", "Ramphastos", "football", "Patrice Talon ");
		        CountryDTORunner dto20=new CountryDTORunner(20, "Bhutan", "Thimphu",787424, true, LocalDate.of( 1910, 3, 8), 20, "Vajrayana Buddhism", "Takin", "Raven", "Archery", "Lotay Tshering");
		        CountryDTORunner dto21=new CountryDTORunner(21, "Bolivia", "La Paz",12388571, false, LocalDate.of( 1825, 8, 6), 9, "Christianity", "Andean Condor", "Andean condor ", "football", "Luis Arce");
		        CountryDTORunner dto22=new CountryDTORunner(22, "Bosnia and Herzegovina", "Sarajevo", 3210847, true, LocalDate.of( 1992, 3, 1), 2, "Orthodox", "Eurasian Wolf", "Vultur", "football", " Zoran Tegeltija");
		        CountryDTORunner dto23=new CountryDTORunner(23, "Botswana", "Gaborone", 2675352, true, LocalDate.of( 1996, 8, 30), 10, "Christianity", "Zebra", "gryphus", "football", " Mokgweetsi Masisi ");
		        CountryDTORunner dto24=new CountryDTORunner(24, "Brazil", "Brasilia", 216422446, false, LocalDate.of( 1822, 8, 7), 26, "Christianity", "Jaguar", "Rufous-bellied thrush", "football", "Jair Bolsonaro");
		        CountryDTORunner dto25=new CountryDTORunner(25, "Brunei", "Bandar Seri Begawan",452524, true, LocalDate.of( 1984, 1, 1), 4, "Islam", "Sultan's Fish", "Turdus rufiventris", "Sepak Takraw","Hassanal Bolkiah");
		        CountryDTORunner dto26=new CountryDTORunner(26, "Bulgaria", "Sofia",6687717, true, LocalDate.of( 1878, 3, 3), 28, "Christianity", "Lion", "Eurasian skylark", "football", "Boyko Borissov");
		        CountryDTORunner dto27=new CountryDTORunner(27, "Burkina Faso", "Ouagadougou",23251485, true, LocalDate.of( 1960, 8, 5), 13, "Islam", "Lion", "Alauda arvensis", "football", "Christophe Joseph Marie Dabire");
		        CountryDTORunner dto28=new CountryDTORunner(28, "Burundi", "Bujumbura",13238559, true, LocalDate.of( 1962, 7, 1), 18, "Christianity", "Lion", "Thaumatibis", "football", "Alain-Guillaume Bunyoni");
		        CountryDTORunner dto29=new CountryDTORunner(29, "Cabo Verde", "Praia",	598682, false, LocalDate.of( 1975, 7, 5), 22, "Christianity", "Lion", "gigantea", "football", "Ulisses Correia e Silva");
		        CountryDTORunner dto30=new CountryDTORunner(30, "Cambodia", "Phnom Penh", 16944826, true, LocalDate.of( 1953, 11, 9), 25, "Theravada Buddhism", "Kouprey", "Giant ibis", "Bokator", "Hun Sen");
		        CountryDTORunner dto31=new CountryDTORunner(31, "Cameroon", "Yaounde",28647293, true, LocalDate.of( 1960, 1, 1), 10, "Christianity", "Lion", "Gavia", "football", "Joseph Dion Ngute");
		        CountryDTORunner dto32=new CountryDTORunner(32, "Canada", "Ottawa", 38781291, true, LocalDate.of( 1960, 7, 1), 10, "Taoism", "North American Beaver", "Common loon", "Ice Hockey", "Justin Trudeau");
		        CountryDTORunner dto33=new CountryDTORunner(33, "Central African Republic", "Bangui", 5742315, true, LocalDate.of( 1960, 8, 13), 16, "Christianity", "African Elephant", "immer", "football", "Firmin Ngrebada");
		        CountryDTORunner dto34=new CountryDTORunner(34, "Chad", "N'Djamena",18278568, true, LocalDate.of(1960, 8, 11), 23, "Sunni Muslims", "African Lion", "Grus ", "football", "Albert Pahimi Padacke");
		        CountryDTORunner dto35=new CountryDTORunner(35, "Chile", "Santiago",19629590, true, LocalDate.of( 1818,8,18), 16, " Roman Catholic", "Andean Condor", "Andean condor", "football", "Sebastian Pinera");
		        CountryDTORunner dto36=new CountryDTORunner(36, "China", "Beijing", 1425671352, false, LocalDate.of(1949,10,1), 23, "Buddhism", "Giant Panda", "Red-crowned crane", "Table Tennis", "Xi Jinping");
		        CountryDTORunner dto37=new CountryDTORunner(37, "Colombia", "Bogota",52085168, true, LocalDate.of( 1810,7,20), 32, "Christianity", " Andean Condor", "Andean condor", "football", "Ivan Duque Márquez");
		        CountryDTORunner dto38=new CountryDTORunner(38, "Comoros", "Moroni",852075, false, LocalDate.of( 1975, 7, 6), 3, "Islam", "Lion", "japonensis", "football", "Azali Assoumani");
		        CountryDTORunner dto39=new CountryDTORunner(39, "Congo (Brazzaville)", "Brazzaville",6106869, true, LocalDate.of( 1960, 8, 15), 12, "Christianity", "African Lion", "African grey parrot", "football", "Clement Mouamba");
		        CountryDTORunner dto40=new CountryDTORunner(40, "Congo(Kinshasa)", "kinshasa", 6106869, false, LocalDate.of(1960, 06, 30), 25, "Christian", " Okapi", "African Fish Eagle", "Soccer", "Sama LuKonde");
				CountryDTORunner dto41=new CountryDTORunner(41, "Costa Rica", "San Jase", 5212173, true, LocalDate.of(1821, 9, 15), 7, "Catholic", "White-tailed deer", "Clay-coloured thrush", "BasketBall", "Carlos Alvarado Quesada");
				CountryDTORunner dto42=new CountryDTORunner(42, "Cote d'Ivoire", "Yamoussoukro", 28873034, false, LocalDate.of(1960, 8, 7), 14, "Muslim", "African Elephant", "Northern Bald Ibis", "Soccer", " Alassane Ouattara");
				CountryDTORunner dto43=new CountryDTORunner(43, "Croatia", "Zagreb", 4008617, true, LocalDate.of(1991, 06, 25), 5, "Catholic", "Marten (Pine Marten)", "Griffon Vulture", "Soccer", "Andrej Plenković");
				CountryDTORunner dto44=new CountryDTORunner(44, "Cuba", "Havana", 11194449, false, LocalDate.of(1902, 05, 20), 15, "Catholic", "Cuban Crocodile", " Cuban Trogon", "Baseball", "Miguel Díaz-Canel");
				CountryDTORunner dto45=new CountryDTORunner(45, "Cyprus", "Nicosia", 1260138, true, LocalDate.of(1960, 07, 16), 13, "Islam", "Cyprus Mouflon (Wild Sheep)", " Cyprus Warbler", "Soccer", "Nicos Anastasiades");
				CountryDTORunner dto46=new CountryDTORunner(46, "Czechia", "Prague", 10495295, false, LocalDate.of(1918, 10, 28), 13, "Atheist", " Double-tailed Lion", "Common Nightingale", "hockey", " Andrej Babiš");
				CountryDTORunner dto47=new CountryDTORunner(47, "Denmark", "Copenhagen", 5910913, true, LocalDate.of(1945, 05, 5), 11, "Evangelical Lutheran", "Mute Swan", "Mute Swan", "Soccer", "Mette Frederiksen");
				CountryDTORunner dto48=new CountryDTORunner(48, "Djibouti", "Djibouti", 1136455, false, LocalDate.of(1977, 06, 27), 6, "Islamic", " Somali Wild Ass", "Arabian Bustard", "Soccer", " Ismaïl Omar Guelleh");
				CountryDTORunner dto49=new CountryDTORunner(49, "Dominica", "Roseau", 73040, true, LocalDate.of(1978, 11, 3), 10, "Christian", " Sisserou Parrot (Imperial Parrot)", "Imperial Amazon Parrot", "Cricket", "Roosevelt Skerrit");
				CountryDTORunner dto50=new CountryDTORunner(50, "Dominican Republic", "Santo Domingo", 11332972, false, LocalDate.of(1844, 02, 27), 31, "Christian", "Palmchat", " Palmchat", "Baseball", "Luis Abinader");
				CountryDTORunner dto51=new CountryDTORunner(51, "East Timor", "Dili", 1360596, true, LocalDate.of(2002, 05, 20), 14, "Catholic", "  Saltwater Crocodile", " Fawn-breasted Whistler", "Soccer", "Taur Matan Ruak");
				CountryDTORunner dto52=new CountryDTORunner(52, "Ecuador", "Quito", 18190484, false, LocalDate.of(1830, 05, 13), 24, "Roman Catholic", " Andean Condor", " Andean Condor", "Soccer", "Guillermo Lasso");
				CountryDTORunner dto53=new CountryDTORunner(53, "Egypt", "Cairo", 112716598, true, LocalDate.of(1922, 02, 28), 29, "Islam", "Steppe Eagle", "Steppe Eagle", "Soccer", " Abdel Fattah el-Sisi");
				CountryDTORunner dto54=new CountryDTORunner(54, "EI Salvador", "San Salvador", 6364943, false, LocalDate.of(1821, 02, 1), 14, "Roman Catholic", "Turquoise-browed Motmot", " Turquoise-browed Motmot", "Soccer", "Nayib Bukele");
				CountryDTORunner dto55=new CountryDTORunner(55, "Equatorial Guinea", "Malabo", 1714671, true, LocalDate.of(1968, 10, 12), 8, "Roman Catholic", " Crested Porcupine", " Grey Parrot", "Soccer", "Teodoro Obiang Nguema Mbasogo");
				CountryDTORunner dto56=new CountryDTORunner(56, "Eritrea", "Asmara", 3748901, false, LocalDate.of(1991, 05, 24), 6, "Christian", "Camel", "White-cheeked Turaco", "Cycling", "Isaias Afwerki");
				CountryDTORunner dto57=new CountryDTORunner(57, "Estonia", "Tallinn", 1332765, true, LocalDate.of(1991, 8, 15), 15, "Christian", "Gray Wolf", "Barn Swallow", "Basketball", "Kaja Kallas");
				CountryDTORunner dto58=new CountryDTORunner(58, "Eswatini", "Mbabane", 1210822, false, LocalDate.of(1968, 9, 06), 4, "Christian", " Lion", "Purple-crested Turaco", "Soccer", "Mswati III ");
				CountryDTORunner dto59=new CountryDTORunner(59, "Ethiopia", "Addis Ababa", 126527060, true, LocalDate.of(1942, 01, 31), 9, "Christian", "  Lion of Judah", " Ethiopian Stork", "Long-distance running", "Abiy Ahmed");
				CountryDTORunner dto60=new CountryDTORunner(60, "Fiji", "Suva", 936375, false, LocalDate.of(1970, 10, 01), 15, "Christian", " Fijian Iguana", " Fiji Wattled Honeyeater", "Rugby union ", "Frank Bainimarama");
				CountryDTORunner dto61=new CountryDTORunner(61, "Finland", "Helsinki", 5545475, true, LocalDate.of(1917, 12, 06), 19, "Christian", "Brown Bear", "Whooper Swan", "Ice hockey ", "Sanna Marin");
				CountryDTORunner dto62=new CountryDTORunner(62, "France", "Paris", 64756584, false, LocalDate.of(1789, 07, 14), 18, "Catholicism", "Gallic Rooster (Coq Gaulois)", " Gallic Rooster (Coq Gaulois)", "Soccer", "Emmanuel Macron");
				CountryDTORunner dto63=new CountryDTORunner(63, "Gabon", "Libreville", 2436566, true, LocalDate.of(1960, 8, 17), 9, "Christian", " Black Panther (Leopard)", " African Fish Eagle", "Soccer", " Ali Bongo Ondimba");
				CountryDTORunner dto64=new CountryDTORunner(64, "The Gambia", "Banjul", 2773168, false, LocalDate.of(1965, 02, 18), 7, "Muslim", "Spur-winged Goose", " Red-necked Nightjar", "Soccer", "Adama Barrow");
				CountryDTORunner dto65=new CountryDTORunner(65, "Georgia", "Tbilisi", 3728282, true, LocalDate.of(1918, 05, 26), 50, "Christian", " Caucasian Leopard", "Golden Pheasant", "Rugby", "Irakli Garibashvili");
				CountryDTORunner dto66=new CountryDTORunner(66, "Germany", "Berlin", 83294633, false, LocalDate.of(1955, 05, 5), 16, "Christian", " Golden Eagle", "White-tailed Eagle", "Soccer", " Angela Merkel");
				CountryDTORunner dto67=new CountryDTORunner(67, "Ghana", "Accra", 34121985, true, LocalDate.of(1957, 03, 01), 16, "Christian", "  Golden Eagle", " African Fish Eagle", "Soccer", "Nana Akufo-Addo");
				CountryDTORunner dto68=new CountryDTORunner(68, "Greece", "Athens", 10341277, false, LocalDate.of(1821, 02, 21), 13, "Christian", "  Dolphin (Common Bottlenose Dolphin)", " Little Owl", "Soccer", " Kyriakos Mitsotakise");
				CountryDTORunner dto69=new CountryDTORunner(69, "Grenada", "Saint George", 126183, true, LocalDate.of(1974, 07, 7), 6, "Christian", " Grenada Dove", " Grenada Dove", "Cricket", " Keith Mitchell");
				CountryDTORunner dto70=new CountryDTORunner(70, "Guatemala", "Guatemala city", 18092026, false, LocalDate.of(1821, 9, 15), 22, "Catholic", "Quetzal", " Resplendent Quetzal", "Soccer", "Alejandro Giammattei");
				CountryDTORunner dto71=new CountryDTORunner(71, "Guinea", "Conakry", 14190612, true, LocalDate.of(1958, 10, 02), 8, "Muslim", " African Elephant", " African Fish Eagle", "Soccer", "Alpha Condé");
				CountryDTORunner dto72=new CountryDTORunner(72, "Guinea-Bissau", "Bissau", 2150842, false, LocalDate.of(1973, 9, 24), 8, "Muslim", "African Fish Eagle", " African Fish Eagle", "Soccer", "Gomes Nabiam");
				CountryDTORunner dto73=new CountryDTORunner(73, "Guyana", "Georgetown", 813834, true, LocalDate.of(1966, 05, 26), 10, "Christian", "Jaguar", " Hoatzin", "Cricket", " Irfaan Ali.");
				CountryDTORunner dto74=new CountryDTORunner(74, "Haiti", "Port-au-prince", 11724763, false, LocalDate.of(1804, 01, 01), 10, "Roman Catholic", "Hispaniolan Trogon", " Hispaniolan Trogon", "Soccer", " Ariel Henry");
				CountryDTORunner dto75=new CountryDTORunner(75, "Honduras", "Tegucigalpa", 10593798, true, LocalDate.of(1821, 9, 15), 18, "Christian", "White-tailed Deer", "Scarlet Macaw", "Soccer", "Orlando Hernández");
				CountryDTORunner dto76=new CountryDTORunner(76, "Hungary", "Budapest", 10156239, false, LocalDate.of(1956, 11, 11), 7, "Christian", "Turul (mythical bird)", "Saker Falcon", "Soccer", " Orbán");
				CountryDTORunner dto77=new CountryDTORunner(77, "Iceland", "Reykjavik", 375318, true, LocalDate.of(1944, 06, 17), 8, "Christian", "Gyrfalcon", "Gyrfalcon", "Soccer", "Katrín Jakobsdóttir");
				CountryDTORunner dto78=new CountryDTORunner(78, "India", "NewDelhi", 1428627663, false, LocalDate.of(1947, 8, 15), 28, "Hinduism", " Bengal Tiger", " Indian Peafowl (Peacock)", "Cricket", " Narendra Modi");
				CountryDTORunner dto79=new CountryDTORunner(79, "Indonesia", "Jakarta", 277534122, true, LocalDate.of(1945, 8, 17), 38, "Islam", " Komodo Dragon", " Javan Hawk-Eagle", "Badminton", "Joko Widodo");
				CountryDTORunner dto80=new CountryDTORunner(80, "Iran", "Tehran", 87590873, true, LocalDate.of(1979, 03,31), 31, "Shaia Islam", "Asiatic lion", "The niightingale", "Wrestling", "Ebrahim Raisi");
				CountryDTORunner dto81=new CountryDTORunner(81, "Iraq", "Baghdad", 4987654, true, LocalDate.of(1932, 10,3), 18, "Islam", "Goat", "Golden Eagle", "Football", "Mohammed Shia Al Sudani");
				CountryDTORunner dto82=new CountryDTORunner(82, "Ireland", "Dublin", 710052314, true, LocalDate.of(1949, 04,18), 32, "christianity", "Mountain hare", "Northern Lapwing", "Gaelic football", "Micchael D Higgins");
				CountryDTORunner dto83=new CountryDTORunner(83, "Israel", "Jerusalem", 9800000, true, LocalDate.of(1949, 05,11), 6, "Jewish", "The Gazelle", "Hoope", "Footbal(Defacto)", "Benjamin Netanyahu");
				CountryDTORunner dto84=new CountryDTORunner(84, "Italy", "Rome", 58853482, true, LocalDate.of(1958, 01,01), 1, "christianity", "The Italian Wolf", "Italian sparrow", "Football", "Giorgio Meloni");
				CountryDTORunner dto85=new CountryDTORunner(85, "Jamaica", "Kingston", 2825544, true, LocalDate.of(1962, 8,06), 14, "christianity", "Billed Streamertail", "jamica Hummingbird", "cricket", "Andrew Holness");
				CountryDTORunner dto86=new CountryDTORunner(86, "Japan", "Tokyo", 125416877, true, LocalDate.of(1947, 03,03), 47, "shinto", "snow Monkey", "Green pheasant", "Sumo", "Fumio Kishida");
				CountryDTORunner dto87=new CountryDTORunner(87, "Jordan", "Amman", 11484805, true, LocalDate.of(1952, 01,11), 12, "Sunni Islam", "Arabian oryx", "Sinai rosefinch", "footbal", "Bisher Khasaweh");
				CountryDTORunner dto88=new CountryDTORunner(88, "Kazakhstan", "Astana", 19944726, true, LocalDate.of(1995, 8,30), 14, "Islam", "horse", "Steppe Eagle", "Baigs", "Alihan Smaiylov");
				CountryDTORunner dto89=new CountryDTORunner(89, "Kenya", "Nairobi", 51526000, true, LocalDate.of(1964, 12,12), 1, "christianity", "Lion", "Lilac breasted roller", "soccer", "William Ruto");
				CountryDTORunner dto90=new CountryDTORunner(90, "Kiribati", "Tarawa", 121388, true, LocalDate.of(1979, 9,20), 21, "christianity", "Magnificent frigate", "frigate bird", "volleyball", "Taneti Maamau");
				CountryDTORunner dto91=new CountryDTORunner(91, "Korea North", "Pyongyang", 26072217, true, LocalDate.of(1971, 12,27), 9, "no religion", "no-animal", "/northerb goshawk", "footbal", "Kim Jong Un");
				CountryDTORunner dto92=new CountryDTORunner(92, "Korea South", "Seoul", 51966948, true, LocalDate.of(1988, 02,25),8, "no religion", "korean tiger", "The magpie", "Teakwondo", "Han Duck soo");
				CountryDTORunner dto93=new CountryDTORunner(93, "Kosovo", "Pristina", 1761985, true, LocalDate.of(2013, 04,19), 38, "Islam", "Balkan iynx", "turdus merula", "football", "Albin Kurti");
				CountryDTORunner dto94=new CountryDTORunner(94, "Kuwait", "KuwaitCity", 4294621, true, LocalDate.of(1961, 11,11), 6, "Islam", "Arabian camel", "Falcon", "football", "Ahmad Nawaf Al sabah");
				CountryDTORunner dto95=new CountryDTORunner(95, "Kyrgyzsran", "Bishkek", 7037590, true, LocalDate.of(1991, 12,26), 7, "Islam", "capra sibirica alaiana", "Buteo hemilasius", "equestrian", "Sadyr Japarov");
				CountryDTORunner dto96=new CountryDTORunner(96, "Laos", "Vientiane", 7749595, true, LocalDate.of(1991, 8,14), 17, "Buddhism", "Elephants", "green peafowl", "Sepak Takraw", "Sonexay siphandone");
				CountryDTORunner dto97=new CountryDTORunner(97, "Latvia", "Riga", 1842226, true, LocalDate.of(1918, 11,18), 110, "christianity", "the bear", "belta cielava", "Ice hockey", "Evika Silina");
				CountryDTORunner dto98=new CountryDTORunner(98, "Lebanon", "Beirut", 5296814, true, LocalDate.of(2005, 04,30), 6, "Islam", "Striped hyena", "Golden Eagle", "Football", "Najib Mikati");
				CountryDTORunner dto99=new CountryDTORunner(99, "Lesotho", "Maeru", 2210646, true, LocalDate.of(1966, 10,4), 10, "christianity", "Black rhinoceros", "no-bird", "football", "Sam Matekane");
				CountryDTORunner dto100=new CountryDTORunner(100, "Liberia", "Monrovia", 5506280, true, LocalDate.of(1847, 07,26), 15, "christianity", "Asiatic lion", "Garden bulbul", "footbal", "George Weah");
				CountryDTORunner dto101=new CountryDTORunner(101, "Libya", "Tripoli", 7252573, true, LocalDate.of(2020, 10,23), 3, "Islam", "Arabian Eagle", "eagle", "football", "Abdul Hamid Dbeibeh");
				CountryDTORunner dto102=new CountryDTORunner(102, "Liechtenstein", "Vaduz", 39584, true, LocalDate.of(1866,8,23), 11, "christianity", "common kestrel", "eagle", "footbal", "Daniel Risch");
				CountryDTORunner dto103=new CountryDTORunner(103, "Lithuania", "Vilnius", 2867725, true, LocalDate.of(1990, 05,1), 10, "christianity", "white stork", " gardras", "Basketball", "Ingrida Nauseda");
				CountryDTORunner dto104=new CountryDTORunner(104, "Luxembourg", "Luxembourg City", 660809, true, LocalDate.of(1958, 1,1), 12, "christianity", "red lion", "The goldcrest", "soccer", "Xavier Bettel");
				CountryDTORunner dto105=new CountryDTORunner(105, "Madagascar", "Antananarivo", 28812195, true, LocalDate.of(1960, 06,26), 23, "christianity", "The Lemur", "fish eagle", "Rugby union", "Christian Ntsay");
				CountryDTORunner dto106=new CountryDTORunner(106, "Malawi", "Lilongwe", 20091635, true, LocalDate.of(1966, 07,06), 28, "christianity", "thompsons gazelle", "african fish eagle", "football", "Lazarus hakwera");
				CountryDTORunner dto107=new CountryDTORunner(107, "Malaysia", "Kuala Lumpur", 33200000, true, LocalDate.of(1963, 9,16), 13, "Sunni Islam", "Malayan tiger", "Rhinoceros hornbill", "Sepak takraw", "Anwar Ibrahim");
				CountryDTORunner dto108=new CountryDTORunner(108, "Maldives", "Male", 521021, true, LocalDate.of(1965, 07,26), 26, "Sunni Islam", "Yellowfin tuna", "white breasted waterhen", "football", "Mohamed Muizzu");
				CountryDTORunner dto109=new CountryDTORunner(109, "Mali", "Bamako", 21359722, true, LocalDate.of(1960, 9,22), 10, "Islam", "the vulture", "the firefinch", "football", "Choguel Kokalla maiga");
				CountryDTORunner dto110=new CountryDTORunner(110, "Malta", "Valletta", 519562, true, LocalDate.of(1964, 9,21), 5, "christianity", "Pharoah Hound", "blue rock thrush", "soccer", "Robert Abela");
				CountryDTORunner dto111=new CountryDTORunner(111, "Marshall Islands", "Delap-Uliga-Djarrit", 42418, true, LocalDate.of(1986, 10,21), 29, "christianity", "Black footed Cat", "common brown noddy", "footbal", "David Kabua");
				CountryDTORunner dto112=new CountryDTORunner(112, "Mauritania", "Nouakchott", 1030000, true, LocalDate.of(1960, 11,28), 15, "Sunni Islam", "Africcan wild cat", "white crowned sparrow", "football", "Mohamed Ould Bilal");
				CountryDTORunner dto113=new CountryDTORunner(113, "Mauritius", "Port Louis", 1265475, true, LocalDate.of(1992, 03,12), 9, "Hinduism", "Sambar deer", "The Dodo", "football", "Pravid Jugnsuth");
				CountryDTORunner dto114=new CountryDTORunner(114, "Mexico", "Mexico City", 129975529, true, LocalDate.of(1917, 02,5), 32, "Roman Catholic", "golden eagle", "eagle", "Charreria", "Ana Lilia Rivera");
				CountryDTORunner dto115=new CountryDTORunner(115, "Micronesia", "Palikir", 104468, true, LocalDate.of(1986, 11,3), 4, "christianity", "Chuuk flying fox", "flyingFox", "Canoe racing", "WesleySimina");
				CountryDTORunner dto116=new CountryDTORunner(116, "Moldova", "Chisinau", 2512758, true, LocalDate.of(1991, 8,27), 5, "christianity", "The wild european bull", "The white stork", "Wrestling", "Dorin Recean");
				CountryDTORunner dto117=new CountryDTORunner(117, "Monaco", "Monaco city", 39050, true, LocalDate.of(1911, 01,5), 1, "christianity", "rabbit", "Lesser Grey Shrike", "football", "Albert II");
				CountryDTORunner dto118=new CountryDTORunner(118, "Mongolia", "Ulaanbaatar", 3227863, true, LocalDate.of(1992, 02,13), 21, "Buddhism", "Przewalskis horse", "saker falcon", "Mongolian wrestling", "Luvsannamsrain");
				CountryDTORunner dto119=new CountryDTORunner(119, "Montenegro", "Podgorica", 602445, true, LocalDate.of(2006, 06,3), 23, "christianity", "Balkan lynx", "Eurasian Griffon vulture", "Water polo", "Dritan Abazovic");
				CountryDTORunner dto120=new CountryDTORunner(120, "Morocco", "Rabat", 37134500, true, LocalDate.of(1945, 11, 18), 12, "Islam","Barbary macaque", "Northern Bald Ibis", "Football (Soccer)","Aziz Akhannouch") ;
				CountryDTORunner dto121=new CountryDTORunner(121, "Mozambique", "Maputo", 32419747, true, LocalDate.of(1975,6,25), 11, "Christianity", "African elephant","Green Coucal", "Football (Soccer)","Carlos Agostinho ") ;
				CountryDTORunner dto122=new CountryDTORunner(122, "Myanmar (Burma)", "Rangoon", 55770232, false, LocalDate.of(1948,1,4), 7, "Buddhism","Burmese peafowl", "Grey Peacock-Pheasant", "Chinlone (a traditional sport)","Min Aung Hlaing") ;
				CountryDTORunner dto123=new CountryDTORunner(123, "Namibia", "Windhoek", 2641857, true, LocalDate.of(1990,3,21), 14, "Christianity","Oryx", "Blue Crane",  "Rugby","Saara Kuugongelwa-Amadhila") ;
				CountryDTORunner dto124=new CountryDTORunner(124, "Nauru", "Yaren", 11832, true, LocalDate.of(1968,1,31), 8, "Christianity", "Nauru Reed Warbler","Nauruan coconut crab", "Australian Rules Football","Lionel Aingimea") ;
				CountryDTORunner dto125=new CountryDTORunner(125, "Nepal", "Kathmandu", 29164578, false, LocalDate.of(1979,10,27), 7, "Hinduism", "Cow","Himalayan Monal",  "Volleyball","Sher Bahadur Deuba") ;
				CountryDTORunner dto126=new CountryDTORunner(126, "Netherlands", "Amsterdam", 17948300, true, LocalDate.of(1581,7,26), 4, "Christianity", "Lion"," Black-tailed Godwit",  "Football (Soccer)","Mark Rutte") ;
				CountryDTORunner dto127=new CountryDTORunner(127, "New Zealand", "Wellington", 5223100, true, LocalDate.of(1962,6,1), 2, "Christianity", "Kiwi","Kiwi", "Rugby","Jacinda Ardern") ;
				CountryDTORunner dto128=new CountryDTORunner(128, "Nicaragua", "Managua", 6733763, true, LocalDate.of(1821,9,15), 15, "Christianity","Resplendent quetzal", " Turquoise-browed Motmot",  "Baseball","Daniel Ortega") ;
				CountryDTORunner dto129=new CountryDTORunner(129, "Niger", "Niamey", 25369415, false, LocalDate.of(1960,8,3), 7, "Christianity", "Giraffe","Dama Gazelle",  "Football (Soccer)","Ouhoumoudou Mahamadou") ;
				CountryDTORunner dto130=new CountryDTORunner(130, "Nigeria", "Abuja",216783400, true, LocalDate.of(1960,10,1), 36, "Christianity","Eagle", "Black Crowned Crane", "Football (Soccer)","Muhammadu Buhari") ;
				CountryDTORunner dto131=new CountryDTORunner(131, "North Macedonia", "Oslo", 1832696, true, LocalDate.of(1991,9,8), 8, "Islam","Eurasian lynx", "Eurasian Magpie", "Football (Soccer)","Zoran Zaev") ;
				CountryDTORunner dto132=new CountryDTORunner(132, "Norway", "Muscat", 25660000, true, LocalDate.of(1814,5,17), 10, "Christianity", "Eurasian elk (moose)","White-throated Dipper",  "Cross-Country Skiing","Erna Solberg") ;
				CountryDTORunner dto133=new CountryDTORunner(133, "Oman", "Islamabad", 5113071, false, LocalDate.of(1650,11,18), 11, "Islam","Arabian oryx", "Arabian Oryx", "Camel Racing","Haitham bin Tariq Al Said") ;
				CountryDTORunner dto134=new CountryDTORunner(134, "Pakistan", "Melekeok", 241499431, true, LocalDate.of(1947,8,14), 4, "Islam","Markhor", "Chukar Partridge", "Field Hockey"," Imran Khan") ;
				CountryDTORunner dto135=new CountryDTORunner(135, "Palau", "Ngerulmud", 16733, true, LocalDate.of(1994,10,1), 16, "Christianity", "Saltwater crocodile","Micronesian Megapode", "Baseball","Surangel Whipps Jr.") ;
				CountryDTORunner dto136=new CountryDTORunner(136, "Palestine", "Jerusalem", 5483450, false, LocalDate.of(1988,11,15), 16, "Islam", " Palestine sunbird"," Palestine Sunbird",  "Football (Soccer)","Mohammad Shtayyeh") ;
				CountryDTORunner dto137=new CountryDTORunner(137, "Panama", "Panama", 4337406, true, LocalDate.of(1821,11,28), 10, "Christianity", "Harpy eagle","Harpy Eagle",  "Baseball","Laurentino Cortizo") ;
				CountryDTORunner dto138=new CountryDTORunner(138, "Papua New Guinea", "Port Moresby", 11781559, true, LocalDate.of(1903,11,3), 20, "Christianity"," Raggiana bird-of-paradise", "Raggiana Bird-of-Paradise",  "Rugby League","Laurentino Cortizo") ;
				CountryDTORunner dto139=new CountryDTORunner(139, "Paraguay", "Asuncion", 6109644, true, LocalDate.of(1975,9,16), 17, "Christianity"," Pampas fox", "Bare-throated Bellbird", "Football (Soccer)","Mario Abdo Benítez") ;
				CountryDTORunner dto140=new CountryDTORunner(140, "Peru", "Lima", 33396698, true, LocalDate.of(1811,5,15), 25, "Christianity","Vicuna", "Andean Cock-of-the-Rock",  "Paleta Frontón (a racquet sport)","Pedro Castillo") ;
				CountryDTORunner dto141=new CountryDTORunner(141, "Philippines", "Manila",110735000, false, LocalDate.of(1821,7,28), 16, "Christianity", "Carabao (water buffalo)","Philippine Eagle",  "Arnis","Rodrigo Duterte") ;
				CountryDTORunner dto142=new CountryDTORunner(142, "Poland", "Warsaw",37691000, true, LocalDate.of(1918,11,11), 16, "Christianity","White-tailed eagle", "White-tailed Eagle",  "Football (Soccer)","Mateusz Morawiecki") ;
				CountryDTORunner dto143=new CountryDTORunner(143, "Portugal", "Lisbon", 10467366, true, LocalDate.of(1640,12,1), 18, "Christianity", "Iberian wolf","Common Nightingale",  "Football (Soccer)","Antonio Costa") ;
				CountryDTORunner dto144=new CountryDTORunner(144, "Qatar", "Doha", 2656032, true, LocalDate.of(1878,12,18), 7, "Islam","Arabian oryx", "Falcon", "Football (Soccer)","Sheikh Khalid bin Khalifa bin Abdulaziz Al Thani") ;
				CountryDTORunner dto145=new CountryDTORunner(145, "Romania", "Bucharest", 19051562, false, LocalDate.of(1971,9,3), 41, "Christianity", "Lynx","Eurasian Lark", "Oin (a traditional Romanian sport)","Nicolae Ciuc") ;
				CountryDTORunner dto146=new CountryDTORunner(146, "Russia", "Mascow", 146424729, true, LocalDate.of(1962,6,1), 89, "Christianity","Russian bear", "Double-headed Eagle", "Bandy","Mikhail Mishustin") ;
				CountryDTORunner dto147=new CountryDTORunner(147, "Rwanda", "Kigali", 13246394, true, LocalDate.of(1876,5,10), 5, "Christianity","African leopard", "African Crowned Crane","Football (Soccer)","Edouard Ngirente") ;
				CountryDTORunner dto148=new CountryDTORunner(148, "Saint Kitts and Nevis", "Basseterre", 10585, false, LocalDate.of(1918,12,1), 11, "Christianity","Brown pelican" ,"Brown Pelican",  "Cricket","Timothy Harris") ;
				CountryDTORunner dto149=new CountryDTORunner(149, "Saint Lucia", "Castries", 5651, true, LocalDate.of(1962,7,1), 12, "Christianity", " Saint Lucia parrot","Saint Lucia Parrot", "Cricket","Philip J. Pierre") ;
				CountryDTORunner dto150=new CountryDTORunner(150, "Saint Vincent and the Grenadines", "Kingstown", 6092, true, LocalDate.of(1983,9,19), 10, "Christianity"," Saint Vincent Amazon parrot", " Saint Vincent Parrot",  "Cricket","Ralph Gonsalves") ;
				CountryDTORunner dto151=new CountryDTORunner(151, "Samoa", "Apia", 2188, true, LocalDate.of(1962,6,1), 11, "Christianity","Samoan flying fox", "Mao", "Cricket","Fiame Naomi Mata") ;
				CountryDTORunner dto152=new CountryDTORunner(152, "San Marino", "San Marino", 15040, false, LocalDate.of(1962,6,1), 9, "Christianity","Italian sparrow", "No designated national bird","Football (Soccer)","Giancarlo Giorgetti" ) ;
				CountryDTORunner dto153=new CountryDTORunner(153, "Sao Tome and Principe", "Sao Tome", 305695, true, LocalDate.of(1975,6,12), 6, "Christianity","Giant sunbird", "Sao Tome Ibis",  "Football (Soccer)","Jorge Bom Jesus") ;
				CountryDTORunner dto154=new CountryDTORunner(154, "Saudi Arabia", "Riyadh", 32175224, true, LocalDate.of(1979,2,22), 13, "Islam", "Arabian horse","Arabian camel", "Football (Soccer)"," Mohammed bin Salman") ;
				CountryDTORunner dto155=new CountryDTORunner(155, "Senegal", "Dakar", 18275743, false, LocalDate.of(1960,4,4), 14, "Islam","African lion", " African Fish Eagle", "Football (Soccer)"," Macky Sall") ;
				CountryDTORunner dto156=new CountryDTORunner(156, "Serbia", "Belgrade", 6641197, true, LocalDate.of(1835,2,15), 29, "Christianity","Gray wolf", "Griffon Vulture","Basketball","Ana Brnabi") ;
				CountryDTORunner dto157=new CountryDTORunner(157, "Seychelles", "Victoria", 396801, false, LocalDate.of(1976,6,29), 26, "Christianity","Seychelles giant tortoise", " Seychelles Black Parrot",  "Volleyball","Wavel Ramkalawan") ;
				CountryDTORunner dto158=new CountryDTORunner(158, "Sierra Leone", "Freetown", 8494260, true, LocalDate.of(1961,4,27), 5, "Islam", "African leopard","White-necked Picathartes","Football (Soccer)","Julius Maada Bio") ;
				CountryDTORunner dto159=new CountryDTORunner(159, "Singapore", "Singapore", 5917600, true, LocalDate.of(1965,8,9), 5, "Buddhism","Lion", "Crimson Sunbird", "Sepak Takraw","Lee Hsien Loong") ;
		        CountryDTORunner dto160 = new CountryDTORunner(160, "Slovakia","Bratislava",5795199,false,LocalDate.of(1992,7,17),79, "Christianity", "BrownBear","GoldenEagle","tennis","RobertFico");
				CountryDTORunner dto161 = new CountryDTORunner(161, "Slovenia","Ljublijana",2119675,true,LocalDate.of(1947,8,15),12, "Christianity", "Balkonhorse","WhiteStork","Basketball","RobertGolob");
				CountryDTORunner dto162 = new CountryDTORunner(162, "Solomon Islands","Honiara",740424,false,LocalDate.of(1978,7,12),9, "Christianity", "Sea turtles","Pigen","Football","Manasseh");
				CountryDTORunner dto163 = new CountryDTORunner(163, "Somalia","Mogadishu",1814337,true,LocalDate.of(1960,6,26),6, "Islam", "leopard","supreb starling","Soccer","HamzaBarre");
				CountryDTORunner dto164 = new CountryDTORunner(164, "South Africa","Pretoria",60414495,false,LocalDate.of(2011,6,9),9, "Christianity", "Springbok","blue crane","Olampic","Suid-Afrika");
				CountryDTORunner dto165 = new CountryDTORunner(165, "South Sudan","Juba",11088796,true,LocalDate.of(2011,9,9),10, "Christianity", "BrownBear","GoldenEagle","soccer","Salva Kiir Mayardit");
				CountryDTORunner dto166 = new CountryDTORunner(166, "Spain","Madrid",47519628,false,LocalDate.of(1985,7,12),17, "Christianity", "Bull","Eagle","football","Pedro Sánchez");
				CountryDTORunner dto167 = new CountryDTORunner(167, "Sri Lanka","Colomba",21893579,true,LocalDate.of(1948,2,4),25, "Buddhism", "Lion","Junglefowl","Cricket","Dinesh Gunawardena");
				CountryDTORunner dto168 = new CountryDTORunner(168, "Sudan","Kharoum",48109006,false,LocalDate.of(1956,1,1),18, "Islam", "Zebra","Secretarybird","Soccer","Hamdok");
				CountryDTORunner dto169 = new CountryDTORunner(169, "Suriname","Paramaribo",623236,true,LocalDate.of(1975,1,25),10, "Christianity", "Lesser Kiskadee","Scarlet Ibis","Soccer","Julius Caesar");
				CountryDTORunner dto170 = new CountryDTORunner(170, "Sweden","Mbabane",10612086,false,LocalDate.of(1523,6,6),25, "Christianity", "Moose","Eagle","hockey","Ulf Kristersson");
				CountryDTORunner dto171 = new CountryDTORunner(171, "Switzerland","Stockholm",8796669,true,LocalDate.of(1921,8,1),26, "Christianity", "Bear","pegien","hockey","Cassis ");
				CountryDTORunner dto172 = new CountryDTORunner(172, "Syria","Bern",23227014,false,LocalDate.of(1946,4,17),14, "Christianity", "BrownBear","ibis","Soccer ","Hussein Arnous");
				CountryDTORunner dto173 = new CountryDTORunner(173, "Taiwan","Damascus",23923276,true,LocalDate.of(1945,10,25),22, "Buddhism", "Formosan black bear"," Blue Magpie","Baseball ","Lin Chuan");
				CountryDTORunner dto174 = new CountryDTORunner(174, "Tajikistan","Taipei",10143543,false,LocalDate.of(1991,11,9),4, "Christianity", "Marco Polo sheep","Formosan","Soccer","Kokhir Rasulzoda");
				CountryDTORunner dto175 = new CountryDTORunner(175, "Tanzania","Dushanbe",67438106,true,LocalDate.of(1961,12,9),10, "Christianity", "Giraffe","Fireback","Soccer","Kassim Majaliwa");
				CountryDTORunner dto176 = new CountryDTORunner(176, "Thailand","Bangkok",71801279,false,LocalDate.of(1960,4,27),77, "Buddhism", "Elephant","Siamese Fireback","Soccer","Srettha Thavisin");
				CountryDTORunner dto177 = new CountryDTORunner(177, "Togo","Lome",9053799,true,LocalDate.of(1970,5,4),30, "Christianity", "Lion","Peregrine","Soccer","Victoire Tomegah");
				CountryDTORunner dto178 = new CountryDTORunner(178, "Tonga","Nukualofa",107773,false,LocalDate.of(1962,8,31),45, "Christianity", "Elephant","Eagle","Rugby ","Siaosi Sovaleni");
				CountryDTORunner dto179 = new CountryDTORunner(179, "Trinidad","portspain",1534937,true,LocalDate.of(1956,3,20),9, "Christianity", "Fiji fauna","Scarlet Ibis","Cricket","Keith Christopher Rowley");
				CountryDTORunner dto180 = new CountryDTORunner(180, "Tunisia","Tunis",12458223,false,LocalDate.of(1991,9,27),24, "Islam", "Camel","Wolf ","football","Ahmed Hachani");
				CountryDTORunner dto181 = new CountryDTORunner(181, "Turkey","Ankara",8575199,true,LocalDate.of(1978,7,1),81, "Islam", "Gray wolf","Wolf ","football","Banili");
				CountryDTORunner dto182 = new CountryDTORunner(182, "Turkmenistan","Ashgabat",6516100,false,LocalDate.of(1995,7,1),5, "Islam", "Bear","pengvine","Soccer","Han Ahmedow");
				CountryDTORunner dto183 = new CountryDTORunner(183, "Tuvalu","Vaiaku",11396,true,LocalDate.of(1945,5,12),6, "Christianity", "dolphin","Lapwing","football ","Kausea Natano");
				CountryDTORunner dto184 = new CountryDTORunner(184, "Uganda","Kampala",48582334,false,LocalDate.of(1962,10,9),111, "Christianity", "Uganda Kob","Grey Crowned Crane","Soccer ","Robinah Nabbanja");
				CountryDTORunner dto185 = new CountryDTORunner(185, "Ukraine","Kyiv",36744634,true,LocalDate.of(1991,8,27),24, "Christianity", "WorldAtlas","crane","Soccer ","Denys");
				CountryDTORunner dto186 = new CountryDTORunner(186, "United Arab Emirates","Abudhabi",9516871,false,LocalDate.of(1971,12,2),7, "Islam", "Peregrine","Peregrine Falcon","Soccer ","Sheikh Mohammed");
				CountryDTORunner dto187 = new CountryDTORunner(187, "United Kingdom","Londan",67736802,true,LocalDate.of(1776,5,4),4, "Christianity", "Lion","European Robin","camel racing","Rishi");
				CountryDTORunner dto188 = new CountryDTORunner(188, "United States","washington",33999656,false,LocalDate.of(1885,7,12),50, "Hindhu", "Bison","Baldeagle","Football","Edi Rama");
				CountryDTORunner dto189 = new CountryDTORunner(189, "Uruguay","Montevideo",3423108,true,LocalDate.of(1825,8,25),6, "Christianity", "Pitangus sulphuratus","GoldenEagle","basketball","José Alberto");
				CountryDTORunner dto190 = new CountryDTORunner(190, "Uzbekistan","Tashkent",35163944,true,LocalDate.of(1991,7,12),12, "Islam", "sand cat","Eagle","football","Abdulla Aripov");
				CountryDTORunner dto191 = new CountryDTORunner(191, "Vanuatu","Portvila",334506,false,LocalDate.of(1980,7,30),6, "Christianity", "Iguna","Lapwing","Soccer","Charlot Salwai");
				CountryDTORunner dto192 = new CountryDTORunner(192, "Vaticancity","Vatican",795199,true,LocalDate.of(1929,2,11),5, "Christianity", "BrownBear","BaldEagle","Soccer","The Pope");
				CountryDTORunner dto193 = new CountryDTORunner(193, "Venezuela","Caracas",28838499,false,LocalDate.of(1811,7,5),23, "Christianity", "Bear","Venezuelan","Baseball","Madruo");
				CountryDTORunner dto194 = new CountryDTORunner(194, "Vietnam","Hanoi",98858950,true,LocalDate.of(1945,9,2),6, "Buddhism", "WaterBafflo"," Venezuelan Troupial","Soccer","Pham Minh Chính");
				CountryDTORunner dto195 = new CountryDTORunner(195, "Yemen","Sanna",34449825,false,LocalDate.of(1967,11,30),21, "Islam", "Arabian leopard"," Vietnamese Pheasant","Soccer","Maeen Abdulmalik Saeed");
				Collection<CountryDTORunner> collection=new ArrayList();
				    collection.add(dto1);
					collection.add(dto2);
					collection.add(dto3);
					collection.add(dto4);
					collection.add(dto5);
					collection.add(dto6);
					collection.add(dto7);
					collection.add(dto8);
					collection.add(dto9);
					collection.add(dto10);
					collection.add(dto11);
					collection.add(dto12);
					collection.add(dto13);
					collection.add(dto14);
					collection.add(dto15);
					collection.add(dto16);
					collection.add(dto17);
					collection.add(dto18);
					collection.add(dto19);
					collection.add(dto20);
					collection.add(dto21);
					collection.add(dto22);
					collection.add(dto23);
					collection.add(dto24);
					collection.add(dto25);
					collection.add(dto26);
					collection.add(dto27);
					collection.add(dto28);
					collection.add(dto29);
					collection.add(dto30);
					collection.add(dto31);
					collection.add(dto32);
					collection.add(dto33);
					collection.add(dto34);
					collection.add(dto35);
					collection.add(dto36);
					collection.add(dto37);
					collection.add(dto38);
					collection.add(dto39);
					collection.add(dto40);
					collection.add(dto41);
					collection.add(dto42);
					collection.add(dto43);
					collection.add(dto44);
					collection.add(dto45);
					collection.add(dto46);
					collection.add(dto47);
					collection.add(dto48);
					collection.add(dto49);
					collection.add(dto50);
					collection.add(dto51);
					collection.add(dto52);
					collection.add(dto53);
					collection.add(dto54);
					collection.add(dto55);
					collection.add(dto56);
					collection.add(dto57);
					collection.add(dto58);
					collection.add(dto59);
					collection.add(dto60);
					collection.add(dto61);
					collection.add(dto62);
					collection.add(dto63);
					collection.add(dto64);
					collection.add(dto65);
					collection.add(dto66);
					collection.add(dto67);
					collection.add(dto68);
					collection.add(dto69);
					collection.add(dto70);
					collection.add(dto71);
					collection.add(dto72);
					collection.add(dto73);
					collection.add(dto74);
					collection.add(dto75);
					collection.add(dto76);
					collection.add(dto77);
					collection.add(dto78);
					collection.add(dto79);
					collection.add(dto80);
					collection.add(dto81);
					collection.add(dto82);
					collection.add(dto83);
					collection.add(dto84);
					collection.add(dto85);
					collection.add(dto86);
					collection.add(dto87);
					collection.add(dto88);
					collection.add(dto89);
					collection.add(dto90);
					collection.add(dto91);
					collection.add(dto92);
					collection.add(dto93);
					collection.add(dto94);
					collection.add(dto95);
					collection.add(dto96);
					collection.add(dto97);
					collection.add(dto98);
					collection.add(dto99);
					collection.add(dto100);
					collection.add(dto101);
					collection.add(dto102);
					collection.add(dto103);
					collection.add(dto104);
					collection.add(dto105);
					collection.add(dto106);
					collection.add(dto107);
					collection.add(dto108);
					collection.add(dto109);
					collection.add(dto110);
					collection.add(dto111);
					collection.add(dto112);
					collection.add(dto113);
					collection.add(dto114);
					collection.add(dto115);
					collection.add(dto116);
					collection.add(dto117);
					collection.add(dto118);
					collection.add(dto119);
					collection.add(dto120);
					collection.add(dto121);
					collection.add(dto122);
					collection.add(dto123);
					collection.add(dto124);
					collection.add(dto125);
					collection.add(dto126);
					collection.add(dto127);
					collection.add(dto128);
					collection.add(dto129);
					collection.add(dto130);
					collection.add(dto131);
					collection.add(dto132);
					collection.add(dto133);
					collection.add(dto134);
					collection.add(dto135);
					collection.add(dto136);
					collection.add(dto137);
					collection.add(dto138);
					collection.add(dto139);
					collection.add(dto140);
					collection.add(dto141);
					collection.add(dto142);
					collection.add(dto143);
					collection.add(dto144);
					collection.add(dto145);
					collection.add(dto146);
					collection.add(dto147);
					collection.add(dto148);
					collection.add(dto149);
					collection.add(dto150);
					collection.add(dto151);
					collection.add(dto152);
					collection.add(dto153);
					collection.add(dto154);
					collection.add(dto155);
					collection.add(dto156);
					collection.add(dto157);
					collection.add(dto158);
					collection.add(dto159);
					collection.add(dto160);
					collection.add(dto161);
					collection.add(dto162);
					collection.add(dto163);
					collection.add(dto164);
					collection.add(dto165);
					collection.add(dto166);
					collection.add(dto167);
					collection.add(dto168);
					collection.add(dto169);
					collection.add(dto170);
					collection.add(dto171);
					collection.add(dto172);
					collection.add(dto173);
					collection.add(dto174);
					collection.add(dto175);
					collection.add(dto176);
					collection.add(dto177);
					collection.add(dto178);
					collection.add(dto179);
					collection.add(dto180);
					collection.add(dto181);
					collection.add(dto182);
					collection.add(dto183);
					collection.add(dto184);
					collection.add(dto185);
					collection.add(dto186);
					collection.add(dto187);
					collection.add(dto188);
					collection.add(dto189);
					collection.add(dto190);
					collection.add(dto191);
					collection.add(dto192);
					collection.add(dto193);
					collection.add(dto194);
					collection.add(dto195);
					System.out.println("Total Countries : "+collection.size());
					Iterator<CountryDTORunner> itr=collection.iterator();
					while(itr.hasNext()) {
						CountryDTORunner countryDto=itr.next();
						System.out.println("Country names:"+countryDto.getName());
					}

			}

		
	}


